// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cllizddjybajveouzxkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsbGl6ZGRqeWJhanZlb3V6eGtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNzgxNDUsImV4cCI6MjA1MDg1NDE0NX0.BJMAiDRUqhOtd3wKORXanuUJIVHeZBDCA9McVK4Li38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);